#!/usr/bin/env bash

# General
alias ls='ls -G'
alias aliases='grep alias < ~/.aliases | cut -c 7- | sort'
alias lsa='ls -lah'
alias mkdir='mkdir -p'
alias chown='chown -Rv'
alias chmod='chmod -Rv'
alias grep='grep --color=auto'
alias psaux='ps aux'
alias psl='psaux|more'
alias psg='psaux|grep'
alias topc='top -o vsize'
alias topm='top -o cpu'
alias meteo='curl -4 http://wttr.in/Moscow'
alias localip='ipconfig getifaddr en0'
alias getnmap='nmap -sP 192.168.1.1/24'
alias week='date +%V'
alias fullupdate='brew update; brew upgrade --all; brew cleanup; sudo gem update --system; sudo gem update; cd $DOTFILES && git pull && cd $BINFILES && git pull'
alias update='cd $DOTFILES && git pull && cd $BINFILES && git pull'
alias mv='mv -v'
alias rm='rm -i -v'
alias cp='cp -v'
alias latest='ls -halt | head'
alias mostused='cut -d " " -f1 ~/.bash_history | sort | uniq -c | sort -nr | head -10'

# Requires specific structure
alias code='cd $PROJECTS'
alias know='cd $PROJECTS/knowledge'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias mu='cd ~/Music'
alias dot='cd $DOTFILES'
alias mybins='ps aux | grep -E "$USER.+bin"'
alias stt='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl ./'
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias gw='cat $PROJECTS/nindo/goals/weekly.md'
alias addweekgoal='vim +  $PROJECTS/nindo/goals/weekly.md'

# Git aliases
alias gclean="git branch --merged | grep -v \"\*\" | xargs -n 1 git branch -d"
alias gp="git pull --prune"
alias gu="git push"
alias gmm="git fetch && git merge origin/master"
alias gsc="git diff --name-only --diff-filter=U"
alias gfm="gmm ; gsc; mur"
alias gop="git-open"
alias gqs="git-quick-stats"
alias grc="git add . && git rebase --continue"
alias gom="git co master"
alias gtoday="git log --since=00:00:00 --all --no-merges --oneline --author=$(git config --get user.email)"
alias g-="git co -"
# alias cii="git add . && git ci -m 'Changed: '$(git diff --name-only --cached -r)'' && git push"

# Specific soft needs to be installed
alias sb='git for-each-ref --sort="-authordate:iso8601" --format=" %(authordate:relative)%09%(refname:short)" refs/heads | ipt | cut -f2 | xargs git co'
alias ci='git add . && node-prepci'
alias mur='ci Merged with master, rebuild'
alias ydl='youtube-dl -f "bestvideo[height<=480,ext=mp4]+bestaudio[ext=m4a]/best[height<=480]"'
alias tweet='t update'
alias pretty='prettier --single-quote --tab-width 4 --write'
alias svgoall='comparemaster | grep svg | while read i; do svgo $i; done'
alias comparegrep='comparemaster | xargs grep -n -e'
alias cme='$DOTFILES/hooks/pre-commit'
alias alfred-backup="tar -zcvf Yandex.Disk.localized/backup/alfredsettings.tar.gz ./alfred-settings"
alias nib="benny-hill-x 8 npm install"
alias dsc="comparemaster | while read i; do echo $i && cat $i | extract-text > ~/temp/checkthis && yasp ~/temp/checkthis && rm -rf ~/temp/checkthis; done"

# GPG
alias gpglk='gpg --list-keys';
alias gpgek='gpg --edit-key';

# Slack statuses aliases
alias ssw='slack-status "working" ":metal:"'
alias sse='slack-status "running an errand, be right back" ":slon_run:"'
alias ssm='slack-status "at a meeting" ":calendar:"'
alias ssa='slack-status "afr" ":rat:"'
alias ssl='slack-status "lunch" ":bento:"'

# Vagrant aliases
alias v='vagrant'
alias vup='vagrant up'
alias vde='vagrant destroy'
alias vss='vagrant ssh'
alias vha='vagrant halt'

# Docker
alias dr='docker run'
alias dri='docker run --rm -it'
alias dp='docker ps -a|grep -v gcr'
alias drm='docker rm'
alias dbi='docker build -t'
alias di='docker images | grep -v gcr'
alias docker-deamon='eval $(minikube docker-env)'

# Disc utils
alias ds="df -P -kHl"

# File size
alias fs="stat -f \"%z bytes\""

# Misc
alias reload='source ~/.bash_profile && echo "Shell config reloaded from ~/.bash_profile"'

# SSH
alias sshdroplet='ssh deploy@192.241.145.243'
