#!/usr/bin/env bash

local ret_status="%(?:%{$fg_bold[green]%} :%{$fg_bold[red]%} %s)"

ZSH_THEME_GIT_PROMPT_PREFIX="(%{$fg[white]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[black]%)%{$fg[red]%} • %{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[black]%) "

spirit_animal () {
    echo "$SPIRIT_ANIMAL"
}

ticket_status () {
  local ref
  if [[ "$(command git config --get oh-my-zsh.hide-status 2>/dev/null)" != "1" ]]
  then
    if [[ $(pwd) == *"avito"* ]] && [[ $(git symbolic-ref HEAD) != *"master"* ]]
    then
      issueStatus=/$(getticket;getprop '/tmp/jira-current-status' 'fields.status.name' | tr '[:upper:]' '[:lower:]')
    else 
      issueStatus=''
    fi
    ref=$(command git symbolic-ref HEAD 2> /dev/null) || ref=$(command git rev-parse --short HEAD 2> /dev/null)  || return 0
    echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$issueStatus$(parse_git_dirty)$ZSH_THEME_GIT_PROMPT_SUFFIX"
  fi
}

min_pwd () {
    echo %{$fg[black]%}%c
}

PROMPT='$(spirit_animal)${ret_status} $(min_pwd) $(ticket_status) %{$reset_color%}'
